zendeskgarden/react-containers

.travis.yml
🤦‍♂️ Turns out it's useful to build the assets before you publish to npm.
We only ran `yarn build:demo` in the `before_deploy` hook so npm published the tarball with no `dist` folder.
I'll run a `lerna publish --force-publish=*` to do a forced patch update.
=> fix: Run yarn build in before_deploy hook

.github/CODE_OF_CONDUCT.md
Fix code of conduct links that got munged by prettier.
designer as a reviewer)~
component~
=> chore: fix malformed Code of Conduct links

README.md
Build is breaking due to `yarn format` making a fix on the readme and causing the git tree to be dirty and the deployment step to abort.
=> fix(build): Missed yarn format change to readme

.eslintrc.json, README.md, package.json, packages/.template/README.md, packages/.template/package.json, packages/.template/src/Example.js, packages/.template/src/ExampleContainer.spec.js, packages/.template/src/useExample.js, packages/.template/stories.js, packages/breadcrumb/README.md, packages/breadcrumb/package.json, packages/breadcrumb/stories.js, packages/keyboardfocus/README.md, packages/keyboardfocus/package.json, packages/schedule/README.md, packages/schedule/package.json, packages/schedule/src/ScheduleContainer.spec.js, packages/schedule/stories.js, packages/selection/README.md, packages/selection/src/useSelection.js, packages/selection/stories.js, yarn.lock
After adding several packages some of the patterns have diverged from each other so Ive brought them all back inline.
- Updated readme to include all published packages so far
- Update template to better reflect starting point
- Made hooks come first and used consistent naming
- Re-added the `zendeskgarden:src` key to package.json as our `jest.resolver.js` file was using it
- Added eslint hooks package
- Add direct link to storybook examples in each package readme.
- Fixed jest warning logs about not using `act` test utility
=> chore: fix inconsistencies with packages

packages/selection/src/useSelection.js
Regardless if the hook is controlled or not we use the `getControlledValue` util to grab the value either internally stored or passed in as arguments.
This fixes a spot where we manage what should have the tabIndex applied it was still using internal state over controlled props which presented itself in `usePagination` .
See pagination PR #20
=> fix(selection): correctly use controlled state to avoid weird bugs

packages/selection/src/useSelection.js
If `onFocus` or `onSelect` are used with the hook the internal state isn't updated correctly as it returns the current state un-modified.
See [codesandbox](https://codesandbox.io/s/38557pq5l1) with container-selection package and it using the `onFocus` argument in the `useSelection` hook. It doesn't actually allow you to increment or decrement the focus state.
This manifested in the `PaginationContainer` example #20
=> fix(selection): check if keyboard select is in controlled mode

packages/focusjail/README.md, packages/focusjail/src/FocusJailContainer.js, packages/focusjail/src/FocusJailContainer.spec.js, packages/focusjail/src/useFocusJail.js, packages/focusjail/stories.js
This changes two things one of them breaking:
- If you tried to do conditional rendering with this e.g. `{condition && <Component />}` the ref created internally wouldn't update and would not be able to focus the container element where focus should be trapped.
- Instead of creating a ref internally to better keep it more flexible a ref should always be passed in by the consumer.
This [issue](https://github.com/thebuilder/react-intersection-observer/issues/162) best describes the problem I was facing that I only came across as I started on the `useModal` hook.
Essentially the passed in ref is stored in state and when it changes we update the state which will re-render with the correct ref.
```js
const [ref, setRef] = useState(containerRef.current);
useEffect(() => { …
```
=> fix(focusjail): Handle conditional rendering and ref passing

packages/keyboardfocus/src/KeyboardFocusContainer.spec.js, packages/keyboardfocus/src/useKeyboardFocus.js
While trying to use the `useKeyboardFocus` hook in our new `react-forms` package I noticed some focus states missing.
With the current implementation items do not display focus when keyboarded to after a `mouseDown` event.
I've corrected this issue with the `setTimeout` implementation that was originally in `react-selection`.  Even though this is a little "hacky" the hooks implementation seems to handle it correctly with `useRef` usage and some timeout cleanup in `useEffect`.
Also, there were some `jest.runOnlyPendingTimer()` calls in the tests already so maybe this was originally part of the implementation?
=> fix(keyboardfocus): allow keyboard focus after mouse event

packages/field/src/index.js, packages/field/src/index.spec.js, packages/selection/src/index.js, packages/selection/src/index.spec.js
This is a breaking change for `field` and `selection` components that removes temporary re-exports of `@zendeskgarden/container-utilities` modules made in #30.
=> chore(field|selection): remove utility re-exports

packages/buttongroup/src/ButtonGroupContainer.spec.js, packages/buttongroup/src/useButtonGroup.js, packages/buttongroup/stories.js, packages/pagination/src/PaginationContainer.spec.js, packages/pagination/src/usePagination.js, packages/pagination/stories.js, packages/selection/src/SelectionContainer.spec.js, packages/selection/src/useSelection.js, packages/selection/stories.js
`useSelection` required a `focusRef` prop for the `getItemProps` prop getter but didn't pass it along as the elements actual `ref` requiring you to do `focusRef` and `ref` to make it work.
A simple change to apply `focusRef` as the `ref` when the `getItemProps` is spread onto an element.
I also improved the errors we throw if you miss applying `item` or `focusRef` it'll now correctly display the right prop getter name.
=> fix(selection|buttongroup|pagination): Pass focusRef through as ref

packages/selection/src/SelectionContainer.spec.js, packages/selection/src/useSelection.js
As defined in the [authoring practices](https://www.w3.org/TR/wai-aria-practices-1.1/#listbox_roles_states_props) a `listbox` should have `aria-orientation` applied based on the keyboard control directions.
Tabs is the main use-case where you can have horizontal or vertical tabs once this is published I'll update #31 to have it.
This defaults to `horizontal` and will remove the attribute if the `both` direction is applied. Should we support `both` direction?
=> fix(selection): Add aria-orientation when direction is changed

packages/breadcrumb/package.json, packages/breadcrumb/stories.js
Remove styling from breadcrumbs example
Hooks are bare bones they shouldn't look like our high fidelity garden react components.
=> docs(breadcrumbs): Remove garden styling from example

packages/selection/src/SelectionContainer.spec.js, packages/selection/src/useSelection.js
If you supplied `onFocus` and correctly managed the state externally the passed in `focusedItem` prop wouldn't actually update the internal reducer.
This was the same issue as #22 with selecting an item and the state not updating correctly.
=> fix(selection): correctly update state if focus is in controlled mode

packages/schedule/src/ScheduleContainer.spec.js, packages/schedule/src/useSchedule.js, packages/schedule/stories.js
In order to support the use case where you want to render something differently based on the delayTimeout we need to expose the state in the hook so a consumer can do that.
This is a breaking change because the hook now returns an object with multiple properties rather than the elapsed time.
```js
const elapsed = useSchedule();
```
```js
const { elapsed, delayMS, delayComplete } = useSchedule();
```
=> feat(schedule): Add state to determine when delay timeout is complete

.lintstagedrc
Recently pushed a major version upgrade of lint-staged which came with some breaking config changes.
Updated config to match new changes.
=> fix: lint-staged upgrade broke due to config changes

.storybook/webpack.config.js, packages/accordion/src/useAccordion.js, packages/breadcrumb/src/useBreadcrumb.js, packages/buttongroup/src/useButtonGroup.js, packages/field/src/useField.js, packages/focusjail/src/useFocusJail.js, packages/keyboardfocus/src/useKeyboardFocus.js, packages/modal/src/useModal.js, packages/pagination/src/usePagination.js, packages/selection/src/useSelection.js, packages/tabs/src/useTabs.js, packages/tooltip/src/useTooltip.js, utils/build/webpack.commonjs.js
Adds some data-attributes `data-garden-container-id` and `data-garden-container-version` to each hook except for container-schedule since it doesn't render any UI or return any prop getters.
I have added some code that is stripped in prod builds so the ids and version show up in dev builds when testing.
=> chore: Add data-garden-container-* attributes

packages/tooltip/README.md, packages/tooltip/src/TooltipContainer.js, packages/tooltip/src/TooltipContainer.spec.js, packages/tooltip/src/useTooltip.js
Passing in the tooltip ref was completely pointless and made it hard to work with.
I believe I was trying to work around the bug fixed here rather than actually needing the ref to the tooltip for any useful reason.
Even though this removes a prop it's not actually a breaking change since you can still pass the ref and it'll work fine, it just doesn't use the ref passed.
I think this react [PR merged](https://github.com/facebook/react/pull/15650) in the latest react (beta/alpha?) might fix the underlying issue and not require the `isMount` tracking.
https://github.com/facebook/react/pull/15650
=> fix(tooltip): don't pass in a ref as it's not actually needed

packages/selection/src/useSelection.js
renovate recently did a non-major upgrade to our deps which moved react from 16.8 to 16.9, this caused the tests to hang and timeout in travis-ci
This is an attempt to fix that
Turns out only in our test env once moving to react 16.9 [the effect](https://github.com/zendeskgarden/react-containers/blob/9d5c5190c435476db0bd39e6ea02ecb841a5fbaa/packages/selection/src/useSelection.js#L157-L163) that monitors the `focusedItem` would get caught in an infinite loop due to it having 2 dependencies that are arrays, `items` & `refs`. This only happens in our jsdom test env not in the actual browser. 
I don't think we need to have `items` & `refs` as deps of the effect as they don't really add anything other than appeasing our eslint exhaustive-deps rules.
But this could also be a weird bug with …
=> fix(selection): Effect gets caught in infinite loop in test env

README.md
To be inline with react-components@next I've added size badges, see example https://bundlephobia.com/result?p=@zendeskgarden/container-buttongroup@0.1.8
zendeskgarden/react-components#413
=> chore: add bundle size badges

packages/modal/src/ModalContainer.js, packages/modal/src/useModal.js
This PR adds the options `focusOnMount` and `environment` to the `useModal`.
The `useModal` hook uses the `useFocusJail` hook to handle the focus for the modal. This hook by default focuses the element on mount and also defaults to using the global `document`.
When using the `useModal` hook, you may want to handle focus yourself, e.g. focusing on an input inside of the modal on mount, and you may also be rendering the modal inside of an iframe, so the global `document` isn't the correct context you are rendering into.
=> Support passing in focusOnMount and environment for the useModal hook

packages/accordion/src/AccordionContainer.spec.js, packages/accordion/src/useAccordion.js, packages/accordion/stories.js
While deprecating the `AccordionContainer` in `react-chrome` I found that the current `useAccordion` hook cannot be controlled. This PR adds an `onChange` callback which allows the component to be controlled.
The previous `useAccordion` hook used the `expandedSections` prop as a "default". To avoid a breaking change I have made it so the hook only becomes controlled if `expandedSections` AND `onChange` are provided.
=> feat(accordion): allow useAccordion hook to become controlled

package.json, packages/.template/src/index.spec.js, packages/accordion/src/index.spec.js, packages/breadcrumb/src/index.spec.js, packages/buttongroup/src/index.spec.js, packages/field/src/index.spec.js, packages/focusjail/src/index.spec.js, packages/focusvisible/src/index.spec.js, packages/keyboardfocus/src/index.spec.js, packages/modal/src/index.spec.js, packages/pagination/src/index.spec.js, packages/schedule/src/index.spec.js, packages/selection/src/index.spec.js, packages/tabs/src/index.spec.js, packages/tooltip/src/index.spec.js, tsconfig.json, utils/build/declarations.d.ts, utils/test/jest.config.js, utils/test/utilities.ts, yarn.lock
The `@zendeskgarden/react-testing` package was removed nearly 4 months ago. Furthermore, `react-containers` should never have a dependency on `react-components`.
https://github.com/zendeskgarden/react-components/pull/342
=> chore: remove deprecated `@zendeskgarden/react-testing` dependency

packages/field/src/useField.ts, packages/field/stories.tsx
Update interfaces for `useField` to allow for custom props being provided. This PR aims to address @austin94's code review comments left [here](https://github.com/zendeskgarden/react-containers/pull/110#pullrequestreview-298415244).
=> fix(field): update field interface

packages/keyboardfocus/src/useKeyboardFocus.js
This PR fixes a bug that does not allow event composition in the `useKeyboardFocus()` hook
=> fix(keyboardfocus): allow events to be composed within useKeyboardFocus() hook

packages/pagination/stories.js
There are React warnings thrown in development mode in the `usePagination` and `paginationConatiner` Storybook example:
[The warnings](https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/ReactDOMUnknownPropertyHook.js#L186) say that the "current" and "focused" attributes must be non-boolean values. But these values are unnecessary and likely was copied over from `react-pagination`. **I went and removed the attributes and the warnings are now gone**.
=> fix(pagination): remove unnecessary attributes

packages/accordion/src/AccordionContainer.ts, packages/breadcrumb/src/BreadcrumbContainer.ts, packages/buttongroup/src/ButtonGroupContainer.ts, packages/field/src/FieldContainer.ts, packages/focusjail/src/FocusJailContainer.ts, packages/selection/src/SelectionContainer.ts, packages/tabs/src/TabsContainer.ts
The proper type annotation for render prop return value to be a type of [`React.ReactNode`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L196). This is because the author of a render prop function can choose to return `null`, or a [`boolean`](https://github.com/zendeskgarden/react-containers/blob/master/packages/modal/stories.js#L100).
Also, the container function component return value should be typecasted as [`React.ReactElement`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L103).
That would mean the code would look like this:
```jsx
export interface IModalContainerProps extends IUseModalProps {
render?: (options: IUseModalReturnValue) => React.ReactNode; 
children?: (options: IUseModalReturnValue) => …
```
=> fix: update render prop function return types

packages/selection/src/SelectionContainer.spec.tsx, packages/selection/src/useSelection.ts
While implementing some `useSelection` usages I found that the current hooks is unintentionally reversing focus order in `vertical` mode with `rtl` enabled.
The hook should not reverse order while in `rtl` mode.
=> fix(selection): correct vertical ordering in RTL mode

packages/.template/src/useExample.js, packages/accordion/src/useAccordion.ts, packages/breadcrumb/src/useBreadcrumb.ts, packages/buttongroup/src/useButtonGroup.ts, packages/field/src/useField.ts, packages/focusjail/src/useFocusJail.ts, packages/keyboardfocus/src/useKeyboardFocus.js, packages/modal/src/useModal.ts, packages/pagination/src/usePagination.ts, packages/selection/src/useSelection.ts, packages/tabs/src/useTabs.ts, packages/tooltip/src/useTooltip.js
Align with `react-components` by providing a `containers.xxx` prefix for all data garden IDs. This will simplify backend processing.
=> chore: add `containers` prefix to `data-garden-container-id` attributes

packages/pagination/src/PaginationContainer.spec.tsx, packages/pagination/src/usePagination.ts, packages/pagination/stories.tsx, packages/selection/src/SelectionContainer.spec.tsx, packages/selection/src/useSelection.ts, packages/tabs/src/TabsContainer.spec.tsx, packages/tabs/src/useTabs.ts
It was discovered that there were accessibility issues with some Storybook examples caused by improper application of aria attributes and roles. The `aria-orientation` property from `useSelection` was improperly applied to `buttongroup` and `pagination` examples. Some aria attributes were improperly used in the `pagination` Storybook..
The `aria-orientation` property has been removed from the `useSelection` hook which prevents `aria-orientation` being applied by default. Consumers that require this property can pass it to the prop getter or apply it to an element manually. For example, it is manually applied in the `useTabs` hook in this PR.
Lastly, the `pagination` Storybook was updated so that `getContainerProps` return value is spread onto the `ul` rather than the `nav`. This applies …
=> fix(selection): remove aria orientation

packages/schedule/src/useSchedule.ts
During the `schedule` package TypeScript refactor, a `NodeJS.Timer` type slipped into `useSchedule.ts`.  **The type for a Timeout is not consistent between the browser and node declarations** and I mistakenly used `NodeJS.Timer`.  Since the hooks are client-side code, `NodeJS` types should be avoided. 
The type is now inferred from the `setTimeout` type.
I went with alternative 1 based on this [S.O.](https://stackoverflow.com/questions/51040703/what-return-type-should-be-used-for-settimeout-in-typescript) answer, but there are different alternatives: 
```jsx
// alternative #1
let loopTimeout: ReturnType<typeof setTimeout>;
loopTimeout = setTimeout(() => {}, 0)
// alternative #2
let loopTimeout: number
loopTimeout = window.setTimeout(() => {}, 0)
// alternative #3
let loopTimeout: number …
```
=> fix(schedule): update timeout type

packages/focusvisible/src/useFocusVisible.js
When migrating this package to TypeScript, I noticed that it was challenging because the document listeners are memoized using `useCallback` when it probably doesn't need to be. Though this isn't a bug, I was finding the code easier to think about without memoization. 
In addition, `removeInitialPointerMoveListeners` is used in a `useCallback` dependency array before it is defined. See [here](https://github.com/zendeskgarden/react-containers/blob/master/packages/focusvisible/src/useFocusVisible.js#L236). This causes TypeScript to complain. This can be resolved with some finagling, but I decided it would be best to propose a refactor which removes the dependency arrays entirely.
Since memoization isn't needed, I removed the calls to `useCallback`, then moved the listeners into the …
=> chore(focusvisible): move callbacks into useEffect

.storybook/webpack.config.js
Story source code is not loading and users only see "Loading...".
This problem occurred after each Storybook example was migrated to TypeScript. To address this problem I updated the `webpack.config.js` so that `stories.tsx` is picked up rather than `stories.js`.
**Before**: "Loading..." persists and source code does not load.
**After**: Source code is loads ✅.
~- [ ] :wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver~
~- [ ] :guardsman: includes new unit tests~
~- [ ] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11~
=> fix: update config to handle stories.tsx

packages/accordion/package.json, packages/accordion/src/useAccordion.ts, packages/field/package.json, packages/field/src/useField.ts, packages/field/stories.tsx, packages/modal/package.json, packages/modal/src/useModal.ts, packages/tabs/package.json, packages/tabs/src/useTabs.ts, packages/tooltip/package.json, packages/tooltip/src/useTooltip.ts, packages/utilities/src/utils/IdManager.ts
Our current ID management solution uses a shared variable that is incremented on each call. This works well for basic use-cases, but is dependent on the render order to be consistent. This can cause issues with SSR and code-splitting scenarios.
We have also seen issues with consumers upgrading dependencies and having duplicate IDs from conflicting `container-utilities` versions.
A popular solution seems to be the [uuid](https://www.npmjs.com/package/uuid) library, but this isn't viable for SSR and reproducible snapshot testing.
Looking through a [react issue](https://github.com/facebook/react/issues/5867) I found a reference to https://www.npmjs.com/package/react-uid which seems to match our use-case well.
Some highlights:
- Provides TS types 😄 
- Includes SSR viable hooks for consumption …
=> feat: move ID utilities to react-uid

packages/pagination/src/PaginationContainer.spec.tsx, packages/pagination/src/usePagination.ts, packages/pagination/stories.tsx, packages/selection/src/useSelection.ts
The a11y defaults from `useSelection` applied to pagination are incorrect. A pagination control is not a `listbox` with `option` elements. Rather it should be a `list` with `listitem` elements. The current page should be identified by `aria-current` rather than `aria-selected`.
The changes fix axe errors currently seen in the examples.
- Pagination container updated to have a role of `list`
- All page items updated to have a role of `listitem`
- Current page identified by `aria-current` (next and previous items are excluded from applying the `ariaSelectedKey`)
- Storybook updated with improved examples:
- `<nav>` labelled to fix axe errors
- There is a current page selected by default
- next/prev page navigation does not run off the ends of the list
- `aria-disabled` applied to prev/next …
=> fix(pagination): accessibility semantics

package.json, packages/accordion/.size-snapshot.json, packages/breadcrumb/.size-snapshot.json, packages/buttongroup/.size-snapshot.json, packages/field/.size-snapshot.json, packages/focusjail/.size-snapshot.json, packages/focusvisible/.size-snapshot.json, packages/keyboardfocus/.size-snapshot.json, packages/modal/.size-snapshot.json, packages/pagination/.size-snapshot.json, packages/schedule/.size-snapshot.json, packages/selection/.size-snapshot.json, packages/tabs/.size-snapshot.json, packages/tooltip/.size-snapshot.json, packages/utilities/.size-snapshot.json, utils/build/rollup.config.js, utils/scripts/build.sh, yarn.lock
During the rollup migration babel wasn't recognizing `ts` and `tsx` files. This fix ensures babel is ran on all files.
=> fix(build): apply babel to all bundles

packages/focusjail/.size-snapshot.json, packages/focusjail/src/FocusJailContainer.spec.tsx, packages/focusjail/src/useFocusJail.ts
In the Modal Storybook example, [keyboard focus is not returned](https://www.w3.org/TR/wai-aria-practices/#dialog_modal#h-note-7) to the trigger element when a user closes a modal. This pull request proposes that the `useFocusJail` hook be updated so that when it unmounts, it is able to return keyboard focus to a trigger element if one was used to render it.
Note this proposal does not completely abstract away keyboard focus management for end-users. In many cases, feature developers will still need to manage keyboard focus when a modal (which implements focus jail) is dismissed. 
Here is a [demo](https://restore-focus.netlify.com/storybook/?path=/story/modal-container--usemodal) for `useModal` Storybook which leverages the updated `useFocusJail` hook.
Closes #159
=> feat(useFocusJail): cache activeElement & restore focus

packages/modal/.size-snapshot.json, packages/modal/src/useModal.ts, packages/modal/stories.tsx
This PR adds a `restoreFocus` argument to the `useModal` hook to allow consumers to have the option of restoring focus. Once this PR is merged, the [`Modal` component](https://github.com/zendeskgarden/react-components/blob/master/packages/modals/src/elements/Modal.tsx#L100) will be updated accordingly.
The demo for this PR can be found here: https://restore-focus-option.netlify.com/storybook/?path=/story/modal-container--usemodal
=> feat(modal): allow optional restore focus

packages/focusvisible/.size-snapshot.json, packages/focusvisible/src/useFocusVisible.ts
The current `useFocusVisible` hook is unable to be used in server side rendering environments. The solution to this is to move the `document` usage from a default variable assignment within a `useEffect` hook.
I have tested this locally with our `ThemeProvider` usage to ensure this now works in SSR environments.
=> fix(focusvisible): allow server side rendering

packages/accordion/src/useAccordion.ts, packages/utilities/src/utils/getControlledValue.ts
This PR updates `getControlledValue` to take a generic and gives consumers TypeScript support.
=> fix(utils): add typing to getControlledValue

packages/accordion/.size-snapshot.json, packages/accordion/src/AccordionContainer.spec.tsx, packages/accordion/src/useAccordion.ts, packages/accordion/stories.tsx
This PR updates the `useAccordion` hook so that it can properly be used as a controlled or uncontrolled hook by updating the API. This PR closes #174. 
* Controlled vs uncontrolled usage is no longer determined by the presence
of an `onChange` handler. 
* Separate controlled state vs. uncontrolled state management. 
- Update uncontrolled state if `isControlled` is `false`.
- Removed initializing uncontrolled state with controlled state.
* Updates Storybook examples to not confuse the usage of controlled vs uncontrolled. Demo is updated to show uncontrolled usage only. If examples of controlled usage if desired, that can be added in a separate PR. 
The demo for this pull request can be found [here](https://heuristic-tereshkova-26cd7e.netlify.com/storybook/?path=/story/accordion-container--u …
=> fix(useAccordion): fix controlled & uncontrolled logic

packages/accordion/CHANGELOG.md
This PR bumps a major release for `container-accordion` as the version bump was missed during the release of #176.
The migration steps for upgrading to the major is included in the updated `CHANGELOG.md`.
The intended squash and merge title will be:
> chore(accordion): update changelog (#184) 
and the intended squash and merge body will be:
> BREAKING CHANGE: Update container-accordion changelog.
>
> The major version for container-accordion was missed when releasing #176. This commit updates container-accordion's CHANGELOG to include information on how to migrate to the new major version.
=> chore(accordion): update changelog 

packages/schedule/.size-snapshot.json, packages/schedule/src/useSchedule.ts
#195 found some issues with our `requestAnimationFrame` cleanup if a consuming component is unmounted at certain time intervals.
This was not only causing invalid `setState` usages, but was causing runaway `requestAnimationFrame` calls (without errors) as well 😨 
This PR introduces a `destroyed` flag which is set during the effect teardown. This allows our `requestAnimationFrame` to check if it has been called during a timeout boundary.
I loaded the codesandbox example locally in storybook and was unable to reproduce the issue with the new changes!
=> fix(schedule): cleanup all animation frames on removal

packages/schedule/.size-snapshot.json, packages/schedule/src/useSchedule.ts
Additional follow-on to #196.
This PR adds an additional `destroyed` check to stop runaway `requestAnimationFrame` calls.
=> fix(schedule): add additional cleanup check for useSchedule

.circleci/config.yml
Pursuant to #216, access to an LTS-tagged executor has been restored, allowing CI version of node to match with project `.nvmrc`.
=> fix: use LTS-tagged node executor

.circleci/config.yml, .github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .huskyrc, README.md, lerna.json, packages/breadcrumb/README.md, packages/schedule/README.md, utils/scripts/deploy.js
This PR updates the Code of Conduct and the branch name references to `main`. Once it is merged into `main`, the `master` branch can be removed and `main` can be set as the default.
=> change: replace master with "main" branch

.storybook/webpack.config.js
This PR removes a `ts-loader` option to ignore implicit any warnings originally caused by `source-loader`. The referenced [issue](https://github.com/storybookjs/storybook/issues/7829) has now been closed and Storybook internally ignores unwanted warnings.
=> chore(webpack): clean up ts-loader option

package.json, packages/accordion/src/AccordionContainer.spec.tsx, packages/buttongroup/src/ButtonGroupContainer.spec.tsx, packages/focusjail/src/FocusJailContainer.spec.tsx, packages/focusvisible/src/FocusVisibleContainer.spec.tsx, packages/keyboardfocus/src/KeyboardFocusContainer.spec.tsx, packages/modal/src/ModalContainer.spec.tsx, packages/pagination/src/PaginationContainer.spec.tsx, packages/selection/src/SelectionContainer.spec.tsx, packages/tabs/src/TabsContainer.spec.tsx, packages/tooltip/src/TooltipContainer.spec.tsx, yarn.lock
This PR adds the [`@testing-library/user-event`](https://www.npmjs.com/package/@testing-library/user-event#typeelement-text-options) package to the project. It also required an update of `@testing-library/dom`.
Most of this PR is a straight forward migration from `fireEvent` to `userEvent`. I saw some opportunity for clean-up and left relevant comments. The largest section of cleanup is located in `SelectionContainer.spec.tsx`. In some areas, I saw an opportunity to use higher [priority queries](https://testing-library.com/docs/guide-which-query) to select elements.
This PR only affects `package.json` and `.spec.tsx` files.
=> chore(tests): add user-event and improve tests

packages/accordion/accordion.stories.tsx
There is an auto-scroll issue (Chromium only) with the accordion Storybook stories. 
Given enough content to scroll in the Accordion stories, the browser quirk will become apparent. It seems like a combination of selecting a focusable element (accordion header button) and a collapse in height (accordion panel) causes Chrome to automatically scroll the window up. 
This auto-scroll issue only occurs given these factors: 
* User is on a Chrome or Edge (Chromium)
* There is enough page content to make the page scrollable
* An Accordion panel _above_ an active accordion header is collapsed
- e.g. `expandable` prop is set to `false` and `collapsible` prop is set to `true`
I've pushed up [a branch](https://github.com/zendeskgarden/react-containers/tree/accordion-scroll-issue) and deployed a …
=> fix(accordion): replace hidden styles to prevent Chromium auto-scroll

packages/tabs/tabs.stories.tsx
This PR updates the Tabs Storybook examples so that each example uses unique refs.
Selecting on the container tab sets focus on the hook tab.
=> fix(tabs): use separate refs for separate examples

packages/focusjail/src/FocusJailContainer.spec.tsx
Strangely the build for the `tabbable` v5 upgrade passed, but the build for `main` failed. This PR fixes the test failure reported in the failed build. It tells `userEvent` that the `tab` event is occurring within a focusjail using the `focusTrap` option.
=> fix(focusjail): use tab focusTrap option in test

packages/selection/.size-snapshot.json, packages/selection/src/useSelection.ts
During the website refactor, we noticed a React [warning](https://github.com/zendeskgarden/website/pull/172#discussion_r498006176) indicating that a set state call happened inside the render cycle. Separately, a [GitHub issue](https://github.com/zendeskgarden/react-components/issues/891) was created, showing this problem affecting the `Tabs` component.
1) Navigate to https://garden.zendesk.com/components/tabs
2) Open the first CodeSandbox [example](https://codesandbox.io/s/6h14p?module=src/Example.tsx)
3) Select a tab from the tabs component in the example
- Both mouse and keyboard selection will trigger the React warning
4) Notice there is a React warning in the JavaScript console ⚠️ 
The warning comes from `onSelect` (or `onChange` in `Pagination`) function call which gets called inside …
=> fix(selection): update reducer to not run side effect

package.json, packages/.template/package.json, packages/accordion/package.json, packages/breadcrumb/package.json, packages/buttongroup/package.json, packages/field/package.json, packages/focusjail/package.json, packages/focusvisible/package.json, packages/keyboardfocus/package.json, packages/modal/package.json, packages/pagination/package.json, packages/schedule/package.json, packages/selection/package.json, packages/tabs/package.json, packages/tooltip/package.json, packages/utilities/package.json, yarn.lock
This PR upgrades the local `react`, `react-dom`, and their relevant TypeScript definitions to React v17. It also upgrades all peerDependency ranges from `^16.8.0` to `>=16.8.0` to include all future `v17` versions. [This syntax aligns with other open-source packages](https://github.com/downshift-js/downshift/blob/master/package.json#L66).
There are [relatively few breaking changes](https://reactjs.org/blog/2020/10/20/react-v17.html), but the updates to `onFocus` and `onBlur` will possibly affect this package more than others. I've manually validated each example, but it would be useful to have your eyes as well.
=> chore(deps): upgrade all packages to React v17

packages/modal/.size-snapshot.json, packages/modal/src/ModalContainer.spec.tsx, packages/modal/src/useModal.ts
Our current `useModal` logic uses `onClick` to recognize when the backdrop is interacted with. To help prevent the modal from closing when the interaction occurs within the bounds of `getModalProps()`. 
I've added a boolean ref that is able to store whether this state. I chose a ref rather a `useState` reference since prop-getters would be re-generated mid click if this state is updated.
=> fix(modals): ensure that modals do not close when click originates within modals

packages/accordion/accordion.stories.tsx, packages/accordion/src/AccordionContainer.spec.tsx
This PR addresses React key warnings seen in both local development and CI tests. The changeset modifies section lists so they contain values that can be used for the `key` prop.
In Storybook React received invalid keys `[object Object]` in the form of refs (`createRef`):
In the tests, React received invalid keys in the form of `undefined`:
=> fix(accordions): provide valid React keys

.storybook/preview-head.html
CSS bedrock link is returning 404. This PR updates the CSS bedrock link.
=> fix: update bedrock CSS link

package.json, yarn.lock
The container [stories aren't loading](https://zendeskgarden.github.io/react-containers/) in the browser. This was due to a recent Renovate merge.
Further investigation shows that there are some errors during TS compilation:
It looks like like `ts-loader` `v9` does not support Webpack 4, so this PR reverts `ts-loader` back to `8.2.0` — which also allows the stories to render.
https://github.com/TypeStrong/ts-loader/issues/595#issuecomment-824240989
=> fix(deps): revert ts-loader for webpack 4 support

README.md
Add new `scrollregion` row to the root REAME table of packages.
fwiw, this PR will test a Netlify site transfer to the new `zendeskgarden` team.
=> chore(docs): add missing scrollregion package to README

packages/selection/.size-snapshot.json, packages/selection/src/SelectionContainer.spec.tsx, packages/selection/src/useSelection.ts
Currently the `@zendeskgarden/container-selection` consumers events event if a modifier is pressed, that prevents for events like `ctrl+enter` to bubble to parents. This PR makes sure that we only listen for the keyboard events we actually should consume.
=> fix(selection): stop hijacking keyboard events with modifier pressed

packages/grid/grid.stories.tsx, packages/grid/package.json, packages/grid/yarn.lock, packages/utilities/.size-snapshot.json, packages/utilities/package.json, packages/utilities/src/index.ts, packages/utilities/src/utils/convertToMatrix.spec.ts, packages/utilities/src/utils/convertToMatrix.ts, packages/utilities/src/utils/useId.ts, packages/utilities/yarn.lock
This PR exports two new utilities from `@zendeskgarden/container-utilities`.
The `useId` is a hook which generates IDs to facilitate WAI-ARIA and server rendering (credit @reach). Future React has [plans](https://github.com/facebook/react/issues/5867#issuecomment-678267054) to support SSR friendly ID generation.
The `convertToMatrix` function converts a flat array to a two-dimension array. It is useful when working with grids (as demonstrated in the `useGrid` stories). It will also be used in `react-components` stories to demonstrate Garden's new color swatch component.
=> feat(utilities): add utilities

packages/grid/grid.stories.tsx, packages/grid/package.json, packages/grid/yarn.lock
In https://github.com/zendeskgarden/react-containers/pull/371, I should have kept using the utility (`convertToMatrix`) and adding it to the `container-utilities` as separate PRs. 
After seeing the [deployment fail](https://app.circleci.com/pipelines/github/zendeskgarden/react-containers/1633/workflows/934e92a5-d672-47da-af57-940fd84639fc/jobs/3199), I realized that CircleCI is probably looking to install an updated `container-utilities` package that hasn't been deployed yet. I should not have added a new utility and used it in the same PR and release.
I would like to remove `container-utilities` from the `grid` package. Once, a release is cut and deployed for the latest `container-utilities`, then the `grid` package can be updated to consume the new utility.
=> fix(grid): revert updated container-utilities until its published

package.json, yarn.lock
Rollback recent `ora` v6 update which breaks the `yarn new` script.
See renovate update in #369
=> fix(deps): rollback dependency ora to v5

packages/tooltip/.size-snapshot.json, packages/tooltip/src/useTooltip.ts
While working on the color swatch component, I noticed that trigger elements that blurred before the `delayMS` resulted in a tooltip that remained visible:
It seems like the `openTooltipTimeoutId` is wiped out when the hook re-renders. This can leave the tooltip in an open state and is noticeable when tooltips are grouped together in a grid. Instead of storing timeout IDs in a variable in scope, they are now stored inside a `useRef` so the timeout IDs can persist the duration of the component's lifecycle.
I wasn't able to come up with a new test because the asynchronous UI is a bit tricky to simulate in the testing environment. Also, no logic has been changed. Feel free to chime in if you have a test suggestion and I can explore + add it!
⚠️ These images showcase the bug and the fix and …
=> fix(tooltip): persist timeout ids

package.json
~~- [ ] **BREAKING CHANGE?** ~~
Fixed the build command for storybook static builds as it was failing.
Removed `-s ./utils/storybook` from `build:demo` command in `package.json` since it was causing local builds to fail.
~~- [ ] :globe_with_meridians: Storybook demo is up-to-date (`yarn start`)~~
~~- [ ] :wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver~~
~~- [ ] :guardsman: includes new unit tests~~
~~- [ ] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11~~
=> build(storybook): omit static source flag in build:demo

.storybook/main.js, .storybook/webpack.config.js, package.json, yarn.lock
~~- [ ] **BREAKING CHANGE?** ~~
Update Webpack to v5 and add storybook support for the new Webpack major.
This PR updates webpack to the latest major release (v5) and adds supporting packages for storybook `builder-webpack5` and `manager-webpack5`, ([following this upgrade guide](https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#upgrade)). By default, storybook uses Webpack v4, which is why it needed these Webpack v5 specific packages installed.
~~- [ ] :wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver~~
~~- [ ] :guardsman: includes new unit tests~~
~~- [ ] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11~~
Due to this being a local dev dependency, some of the checks above were omitted since they do not apply to the packages …
=> chore(deps): update webpack to v5

packages/utilities/.size-snapshot.json, packages/utilities/src/utils/useCombinedRefs.ts
Deprecating `useCombinedRefs` as it will be removed in next major release.
Deprecation of `useCombinedRefs` was supplemented with `@deprecation` tag and a console warning to alert future consumers of the upcoming removal in the next major release.
=> chore(utilities): deprecate useCombinedRefs hook

packages/grid/src/GridContainer.spec.tsx
Fixed `GridContainer` tests for better coverage.
In the `GridContainer.spec`, the `GridContainer` was directly imported from file instead from `index.js` preventing full coverage for `index.js`.
`GridContainer` wasn't getting full coverage in the tests because it was using hooks `useGrid` instead of renderProps; thus didn't render `GridContainer`.
=> chore(grid): Replace useGrid to use GridContainer for better test coverage

.storybook/main.js, .storybook/webpack.config.js
Adds support for IE 11 when using Storybook with Webpack 5.
Although the current transpilation of `react-containers` is ES5 compatible (thanks to Babel), both the Storybook UI manager and iframe preview were using JavaScript syntax (ES6) due to the Webpack 5 runtime configuration. ES6 is only supported in modern browsers and this PR configures the UI manager and preview builds to use only ES5 syntax throughout the runtime.
=> chore(storybook): support ie11 with webpack 5

packages/accordion/.size-snapshot.json, packages/accordion/src/AccordionContainer.spec.tsx, packages/accordion/src/useAccordion.ts
This pull request adds a `defaultExpandedSection` prop to allow uncontrolled `useAccordion` usages to set default expanded sections.
The accordion story isn't structured to demonstrate uncontrolled (or controlled) behavior. Feel free to pull the branch down locally and update the story's prop manually to see the behavior:
```jsx
// uncontrolled usage with default state
useAccordion({ expandable, collapsible, defaultExpandedSections: [0, 1, 2, 3, 4] });
```
=> feat(accordion): add default expanded sections prop

packages/utilities/.size-snapshot.json, packages/utilities/src/index.ts, packages/utilities/src/utils/ContainerOrientation.ts, packages/utilities/src/utils/DocumentPosition.ts, packages/utilities/src/utils/KEY_CODES.ts, packages/utilities/src/utils/KeyboardEventValues.ts
- Created DocumentPosition enum
- Created ContainerOrientation enum
- Added the Asterisk keycode to KEY_CODE
- Created KEYS dictionary using Key Values
These changes are required by https://github.com/zendeskgarden/react-containers/pull/346 
This PR introduces two new enums and a dictionary in the utilities package. 
`DocumentPosition` is an enum containing the bitmask needed to determine the position of an element relative to another as defined in: https://developer.mozilla.org/en-US/docs/Web/API/Node/compareDocumentPosition
`ContainerOrientation` is a simple enum aimed at bringing consistency across the different containers. I noticed different terms for the same feature. A common `orientation` option using this enum would be useful. 
The use of `event.keyCode` has been deprecated and …
=> feat(utilities): Created DocumentPosition, ContainerOrientation and KEYS

packages/splitter/yarn.lock
Correct missing lockfile updates for Splitter to allow build to pass.
=> chore(lock): update lockfile

.github/renovate.json
This PR removes options from the Renovate config due to causing failures in our dependency update PRS.
Removes [`postUpdateOptions`](https://docs.renovatebot.com/configuration-options/#postupdateoptions) and [`postUpgradeTasks`](https://docs.renovatebot.com/configuration-options/#postupgradetasks) from the configuration since both are only meant to run in self-hosted instances.
Addresses [issue #13810](https://github.com/renovatebot/renovate/issues/13810) and [discussion #13903](https://github.com/renovatebot/renovate/discussions/13903). It turns out the two configuration options were ignored initially and now throw when used due to a recent change by Renovate.
=> chore(renovate): remove post update from config

packages/modal/src/useModal.ts
The types for `onClose` handler should satisfy synthetic event constraints because consumers pass this handler to React components (e.g. `<button onClick={onClose} />`.
Previously, a native event type was used and that caused issues upstream where consumers had to [cast the event type](https://github.com/zendeskgarden/react-components/blob/6bcf661282e629b3482c214192475f47174c1aa7/packages/modals/demo/stories/ModalStory.tsx#L26) as `any` because the lower level `container-modal` handler type did not support synthetic events.
There will be a follow-on PR in `react-components` to address the type issues when using `container-modal`.
=> fix(modals): use synthetic types for close handler

packages/pagination/README.md, packages/pagination/demo/#readme.stories.mdx, packages/pagination/demo/pagination.stories.mdx, packages/pagination/demo/stories/PaginationStory.tsx, packages/pagination/src/index.ts
Following #420, update storybook for the `pagination` package.
=> chore(pagination): refactor storybook

packages/splitter/.size-snapshot.json, packages/splitter/src/useSplitter.ts
Fixes bugs prior to merge of https://github.com/zendeskgarden/react-components/pull/1339
Fixes the following scenarios:
- After mouse down, the separator is not focused and keys do not move separator
- On position leads, the keyboard up would move separator down and keyboard down would move separator up
=> feat(splitter): fixes focus on pointer and adds a horizontal keyboard map

packages/grid/.size-snapshot.json, packages/grid/README.md, packages/grid/demo/grid.stories.mdx, packages/grid/demo/stories/GridStory.tsx, packages/grid/src/GridContainer.spec.tsx, packages/grid/src/GridContainer.tsx, packages/grid/src/useGrid.ts
The initial `useGrid` hook implementation conflated [data](https://www.w3.org/TR/wai-aria-practices/#dataGrid) vs. [layout](https://www.w3.org/TR/wai-aria-practices/#layoutGrid) by injecting a selection model that does not apply to the child DOM structure. This particular Garden grid implementation was built to facilitate a layout structure for the [`ColorSwatch` component](https://garden.zendesk.com/components/color-swatch) – which provides its own selection (i.e. not based on a `gridcell` marked as `aria-selected`) as a group of options. The container simply provides navigation primitives for the row/column layout. While there is room to enhance Garden's existing container, there are a couple of guiding quotes from WAI-ARIA that are illuminating:
> [ref: …
=> fix(grid)!: remove selection

packages/splitter/.size-snapshot.json, packages/splitter/demo/splitter.stories.mdx, packages/splitter/demo/stories/SplitterStory.tsx, packages/splitter/package.json, packages/splitter/src/SplitterContainer.spec.tsx, packages/splitter/src/SplitterContainer.tsx, packages/splitter/src/index.ts, packages/splitter/src/types.ts, packages/splitter/src/useSplitter.ts, packages/splitter/yarn.lock
This PR is a follow-on to #461 with a refactored `useSplitter` codebase and simplification (note the reduced size) of the API. The following are key elements of change:
- [breaking] make `aria-label` a required attribute of `getSeparatorProps` (will fix the missing label in `react-components`)
- [breaking] use standard `isLeading` & `isFixed` boolean types rather than `position` and `type` enums
- [breaking] shift `environment` to be optional and work off `document` rather than `window` context for API consistency
- [breaking] added `separatorRef` as a required prop. This aligns the API with other Garden containers and eliminates an awkward ownership problem where the previous returned `ref` had to merge and spread in the right order. The consumer should own element ref assignments.
- …
=> fix(splitter)!: refactor with improved type interfaces

packages/field/.size-snapshot.json, packages/field/README.md, packages/field/demo/field.stories.mdx, packages/field/demo/stories/FieldStory.tsx, packages/field/src/FieldContainer.spec.tsx, packages/field/src/FieldContainer.tsx, packages/field/src/index.ts, packages/field/src/types.ts, packages/field/src/useField.ts
This PR adds `getMessageProps` as a return value to use with an additional message component.
The `getMessageProps` is used to connect the input `aria-describedby` attribute as one of the space separated IDs (see [ID reference list](https://www.w3.org/TR/wai-aria/#typemapping)) that describe the element. 
Internally, the `getInputProps` has a new option added: `containsMessage`. This allows the container to only add the `messageId` to the `aria-describedby` only if it is set to true. If there is a preference to rename this option name (eg `hasMessage`), open to renaming it.
=> feat(field): add getMessageProps prop getter to container

packages/scrollregion/package.json, packages/scrollregion/yarn.lock
This PR removes an unused dependency `react-merge-refs` in `scrollregion`.
=> chore(scrollregion): remove unused react-merge-refs package

packages/slider/.size-snapshot.json, packages/slider/src/useSlider.ts
The initial port over from `react-components` missed the `event.preventDefault()` call on keyboard interactions.
The fix was tested against https://github.com/zendeskgarden/react-components/pull/1431.
=> fix(slider): prevent default screenreader cursor navigation

packages/splitter/.size-snapshot.json, packages/splitter/src/SplitterContainer.spec.tsx, packages/splitter/src/useSplitter.ts
Update the current `useSplitter` hook to use [WAI-ARIA specified](https://www.w3.org/WAI/ARIA/apg/patterns/windowsplitter/) actions and values:
- `<Enter>` "restores the splitter to its previous position" (not from `min` to `max`)
- typical `aria-valuemin` and `aria-valuemax` are normalized to values between 0 and 100 (see https://www.w3.org/WAI/ARIA/apg/patterns/windowsplitter/#wai-aria-roles-states-and-properties-27)
Additional fixes/enhancements include:
- prevent default browser scroll on cursor keys
- a mouse double-click action maps to `<Enter>`
=> fix(splitter): use WAI-ARIA specified actions and values

packages/splitter/.size-snapshot.json, packages/splitter/demo/splitter.stories.mdx, packages/splitter/demo/stories/SplitterStory.tsx, packages/splitter/src/SplitterContainer.spec.tsx, packages/splitter/src/useSplitter.ts
Allow `isFixed` splitter to leverage `lastPosition` state handling.
Also, unwinds a controlled component re-render bug introduced by #487.
=> fix(splitter): update `isFixed` to leverage enter key handling

.github/renovate.json
Re-adding postUpdateOptions to renovate configuration to de-dupe dependencies with yarn.
=> chore(renovate): add postUpdateOptions to config

packages/field/yarn.lock
The updated `yarn.lock` is causing [CI failures](https://app.circleci.com/pipelines/github/zendeskgarden/react-containers/2995/workflows/905e9efd-1428-4c60-9c25-7a5cdb07399b/jobs/5704)
=> fix(field): update yarn.lock

packages/grid/.size-snapshot.json, packages/grid/demo/grid.stories.mdx, packages/grid/demo/stories/GridStory.tsx, packages/grid/package.json, packages/grid/src/GridContainer.spec.tsx, packages/grid/src/GridContainer.tsx, packages/grid/src/index.ts, packages/grid/src/types.ts, packages/grid/src/useGrid.ts, packages/grid/src/utils.ts
includes:
- consistent `rowIndex` & `colIndex` naming for `getGridCellProps`
- narrowed `HTMLProps` typing with `Element` extension generics
Similar to #516, this PR refactors `grid` interface types for consistency and prepares the hook for inclusion in `useCombobox` branch work. Adds critical missing `useId` generation as the current hook would only support one active, default grid on the page due to ID collision. Also fixes SSR-unsafe `environment` instantiation.
Opportunistic updates:
- added `getGridProps` to help enforce ARIA labeling
- handle matrix mutation by ensuring `tabIndex` remains valid
- `useCallback` and `useMemo` patterns applied
=> fix!(grid): refactored interface types for enhanced accessibility and provide missing ID generation

packages/combobox/.size-snapshot.json, packages/combobox/src/ComboboxContainer.spec.tsx, packages/combobox/src/types.ts, packages/combobox/src/useCombobox.ts
Consumers need access to environment as `window` rather than `document` in order to render Downshift in environments such as shadow DOM. In addition:
- restores a blur event handler (bug introduced in 1791d0c) that is intended for Garden-only (vs. Downshift) layouts
- removes invalid `aria-expanded` from a Garden layout trigger (contains input)
- passes ref type generics through `useCombobox`
- allows disabled options to be `aria-selected`
Unlike the current combobox seen in https://zendeskgarden.github.io/react-containers/?path=/story/packages-combobox--uncontrolled&args=layout:Downshift, this PR's storybook deployment can successfully expand Downshift trigger layout via mouse.
=> fix!(combobox): update environment to be of type `Window` rather than `Document`

packages/combobox/.size-snapshot.json, packages/combobox/demo/combobox.stories.mdx, packages/combobox/demo/stories/ComboboxStory.tsx, packages/combobox/src/ComboboxContainer.spec.tsx, packages/combobox/src/ComboboxContainer.tsx, packages/combobox/src/types.ts, packages/combobox/src/useCombobox.ts, packages/combobox/src/utils.ts
The current `any` type is allowing the combobox to key on null-ish values such as `undefined` or `null`. Neither Downshift or Garden's useCombobox are geared to handle null-ish option values for selection, etc. This PR restricts the type, but still allows for complex `object` values. Allowing `number` was considered, but not applied due to the false-y case for `0` and the fact that numbers can easily be converted to strings by the consumer before providing them to the hook.
=> fix!(combobox): update option value to be `string | object` rather than `any`; remove `isAutocomplete=true` default

packages/combobox/.size-snapshot.json, packages/combobox/src/ComboboxContainer.spec.tsx, packages/combobox/src/useCombobox.ts
The current combobox "sticks" expanded when tabbing out for `isMultiselectable={true}` and `isEditable={false}`. This fix ensures that the listbox collapses when the non-editable combobox is blurred.
The problem can currently be seen here: https://zendeskgarden.github.io/react-containers/?path=/story/packages-combobox--uncontrolled&args=isEditable:false;isMultiselectable:true
=> fix(combobox): ensure listbox collapse on non-editable combobox blur

packages/combobox/.size-snapshot.json, packages/combobox/src/useCombobox.ts
This update fixes for controlled component re-renders that reset `activeIndex` to the currently selected option. Needed to unblock `<Combobox>` HOC.
=> fix(combobox): prevent Downshift from overriding controlled `activeIndex`

packages/combobox/.size-snapshot.json, packages/combobox/package.json, packages/combobox/src/useCombobox.ts, packages/combobox/yarn.lock
- prevent selection from altering active index
- handle controlled actions
- add disabled option ID
- scroll input into view on focus
This change fixes a flash of `aria-activedescendant` that occurs as the HOC listbox is animating collapsed and ensures controlled `onChange` handlers are called for Downshift actions (which rolls back #540).
=> fix(combobox): handle controlled actions

packages/combobox/.size-snapshot.json, packages/combobox/src/ComboboxContainer.spec.tsx, packages/combobox/src/useCombobox.ts
Fixes an issue where the input retains focus under the following circumstances:
1) user removes a tag
2) and then attempts to navigate away from the component
=> fix(combobox): prevent multiselectable from retaining focus on tag removal

packages/combobox/.size-snapshot.json, packages/combobox/src/ComboboxContainer.spec.tsx, packages/combobox/src/useCombobox.ts
For select-only (`isEditable={false}`) combobox:
- Adds `preventDefault` to avoid page scroll when pressing keyboard `space`
- Attaches same ☝️ behavior to tags for `isMultiselectable`
- Adds selection on `enter`/`space`
Reference https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/#kbd_label
=> fix(combobox): handle select-only collapse listbox on space/enter

packages/tabs/.size-snapshot.json, packages/tabs/src/useTabs.ts
Optimizes the `useTabs` hook for more performant consumption.
By memoizing callbacks and the return value of `useTabs` container, this will reduce re-rendering (and recomputing) of consuming components on every render. The use of `useCallback` and `useMemo` will persist object references until it is necessary to update.
=> fix(tabs): minimize re-rendering of container by memoization

packages/utilities/package.json
This removes `prop-types` from `peerDependencies` in `react-containers`. It isn't being used within `react-containers` and causes a warning to be displayed if you install the package and don't have `prop-types` installed in your `package.json`.
=> fix(utilities): remove unused prop-types peerDep from container-utilities

packages/combobox/.size-snapshot.json, packages/combobox/src/useCombobox.ts
The connective tissue between focused tag and expanded listbox active index proves to be problematic due to underlying Downshift `setHighlightedIndex` state management. In the `Combobox` HOC, the re-render is causing an unexpected loss of component focus. Since this functionality is neither  a usability or accessibility concern, we are removing it here in prep for a corresponding fix in `react-components`.
=> fix(combobox): remove problematic tag focus handling

packages/accordion/.size-snapshot.json, packages/accordion/README.md, packages/accordion/demo/accordion.stories.mdx, packages/accordion/demo/stories/AccordionStory.tsx, packages/accordion/demo/stories/data.ts, packages/accordion/package.json, packages/accordion/src/AccordionContainer.spec.tsx, packages/accordion/src/AccordionContainer.tsx, packages/accordion/src/index.ts, packages/accordion/src/types.ts, packages/accordion/src/useAccordion.ts, packages/accordion/yarn.lock
Adds a new `sections` prop to explicitly define each section. Moving forward, `sections` will be needed for the `useAccordion` container to work properly. There have been additional changes to the distribution exports.
=> feat(accordion)!: add sections prop

package.json, packages/slider/src/useSlider.ts, yarn.lock
Reverting `prettier` to v2 as it is causing failure when tagging releases.
=> chore(deps): revert prettier to v2

package.json, packages/utilities/.size-snapshot.json, packages/utilities/src/utils/useId.spec.tsx, packages/utilities/src/utils/useId.ts, yarn.lock
Provide an `idCounter` fallback (same as used by the legacy [IdManager](https://github.com/zendeskgarden/react-containers/blob/main/packages/utilities/src/utils/IdManager.ts)) for SSR environments that produce `undefined` IDs.
Verified the patch by testing the compiled `dist` with a build of the Garden website.
=> fix(utilities): update `useId` to handle SSR

packages/combobox/.size-snapshot.json, packages/combobox/src/useCombobox.ts, packages/utilities/src/utils/useId.spec.tsx, packages/utilities/src/utils/useId.ts
Prior to this PR, `useId` was called and IDs/ID prefixes were handed off to both the Garden `useField` and Downshift `useCombobox` hooks. Upon hydration, `useField` was updated with the underlying `@reach/auto-id` layout effect. But Downshift puts IDs in a ref, where they are not updated. The effect is ID mismatch between label & input.
By wrapping the `useId` call in `useRef`, we prevent the ID state update on hydration and cross-references remain stable.
=> fix(combobox): stabilize ID prefix

packages/combobox/.size-snapshot.json, packages/combobox/src/useCombobox.ts, packages/field/.size-snapshot.json, packages/field/src/FieldContainer.spec.tsx, packages/field/src/useField.ts
This PR centralizes ID control within `useCombobox`, preventing either of the underlying hooks (`useDownshift` & `useField`) from generating IDs. With effects in play, partial rerenders could inadvertently bump and invalidate component ID relationships. These relationships are now maintained throughout the lifetime of the component.
=> fix(combobox): stabilize ID usage

packages/combobox/.size-snapshot.json, packages/combobox/src/useCombobox.ts
The memoization of IDs in [dcd27eb](https://github.com/zendeskgarden/react-containers/pull/580/commits/dcd27ebaac493390e6aac9cf488b432f3d26c577) continues to allow partial state change if the prefix updates per layout effects. The PR tucks IDs in a ref that won't cause unwanted rerender. This means that the `prefix` prop cannot be dynamically updated – but that isn't behavior we really want to encourage anyway.
=> fix(combobox): address stable ID regression

packages/menu/src/MenuContainer.spec.tsx, packages/menu/src/useMenu.ts
- Minor change to `getItemProps` to allow prop spread override. 
- Wrap unit test user actions in `act` to suppress warnings
=> fix(menu): allow prop spread override in getItemProps

packages/menu/.size-snapshot.json, packages/menu/demo/stories/MenuStory.tsx, packages/menu/demo/stories/data.ts, packages/menu/src/MenuContainer.spec.tsx, packages/menu/src/types.ts, packages/menu/src/useMenu.ts
Enables default selection of items in an uncontrolled menu by adding `selected: true` to a given item.
Includes a couple miscellaneous refactors/renaming & small typing fix for `IMenuItemBase`.
~~:wheelchair: tested for [WCAG 2.1](https://www.w3.org/TR/WCAG21) AA compliance~~
=> feat(menu): enables initial selected items

packages/combobox/.size-snapshot.json, packages/combobox/demo/~patterns/patterns.stories.mdx, packages/combobox/demo/~patterns/stories/IMEStory.tsx, packages/combobox/demo/~patterns/stories/data.ts, packages/combobox/src/ComboboxContainer.spec.tsx, packages/combobox/src/useCombobox.ts
The Downshift `useCombobox` hook currently has an issue that prevents IME from entering expected values in a controlled combobox. This [workaround](https://github.com/downshift-js/downshift/issues/1108#issuecomment-842407759) re-invokes `onChange` with the correct composed input value. The majority of the PR is the introduction of a new "IME" pattern storybook demo so that future updates can be tested with IME without interference from `useArgs`.
**Before**
**After**
https://github.com/downshift-js/downshift/issues/1452
=> fix(combobox): handle IME via controlled input `onChange` override

packages/menu/.size-snapshot.json, packages/menu/src/useMenu.ts
A subtle but non-breaking API change to make `selectedItems` updates predictable between `radio` and `checkbox` item selection.
Currently, `radio` and `checkbox` selection  is handled differently depending on if a `'checkbox'` or `'radio'` item is selected.
**Current behavior:**
- Checkbox: selected item is pushed into `selectedItems`.
- Radio: selected item is replaces the previously selected radio item (e.g., it has a matching `name`), otherwise it is pushed into `selectedItems`.
The inconsistency of selection handling here might be confusing if a consumer wants to have alternate behavior between item types.
**This PR proposes:**
- Checkbox: selected item is pushed into `selectedItems`.
- Radio: selected item is pushed into `selectedItems` (if another item in the set has a matching …
=> fix(menu): provide consistent selection behavior in `selectedItems` data

packages/menu/.size-snapshot.json, packages/menu/src/useMenu.ts
The keydown handler on menu items has an over-eager trigger focus condition that always moves focus back to the trigger element as long as the chosen item isn't enabling nested/sub-menu behavior.
By fixing that condition (see [detail](#Detail) below), the menu hook enables consumers to retain expansion without losing focus within the menu, even during item selection, if desired.
Here is a [reproduction](https://codesandbox.io/s/menu-trigger-focus-bug-srr7l2) of the incorrect behavior (use keyboard to select an item).
The fix relies on a central conditional in `useEffect` that waits for the menu to be properly closed before trying to focus the trigger. A ref is used to track if the trigger should or shouldn't be focused, and once the menu is closed and ref is `true`, the trigger can be …
=> fix(menu): prevents over-eager trigger focus when items are selected via keyboard

packages/combobox/demo/stories/ComboboxStory.tsx, packages/combobox/demo/stories/data.ts, packages/combobox/src/ComboboxContainer.spec.tsx, packages/combobox/src/types.ts, packages/combobox/src/useCombobox.ts
A [nested](https://garden.zendesk.com/components/combobox#nested) multiselectable combobox must render selected options at every level of the listbox. The addition of the `hidden` attribute allows selected options to be accessibly rendered – even outside their visual sub-level. This PR provides the necessary baseline for enhancing the `Combobox` component in `react-components`.
=> feat(combobox): add support for `hidden` options

package-lock.json, package.json, packages/accordion/src/AccordionContainer.spec.tsx, packages/accordion/src/useAccordion.ts, packages/tooltip/src/TooltipContainer.spec.tsx, packages/tooltip/src/useTooltip.ts, utils/build/rollup.config.js
The `KEY_CODES` utility is now deprecated.
Also cleans up the `acornInjectPlugins` option which is no longer recognized by Rollup. The same was removed in https://github.com/zendeskgarden/react-components/pull/1641 several months ago.
=> chore: replace deprecated `KEY_CODES` with `KEYS` constants

packages/combobox/src/ComboboxContainer.spec.tsx, packages/combobox/src/useCombobox.ts
The Downshift `useCombobox` hook currently has an issue that jumps the input cursor to the end while attempting to modify a _controlled_ `inputValue`. This [workaround](https://github.com/downshift-js/downshift/issues/1108#issuecomment-674180157) manages `inputValue` state locally. 
**Before**
https://github.com/zendeskgarden/react-containers/assets/143773/d0df995d-14c4-446e-b469-8aad7cd63914
**After**
https://github.com/zendeskgarden/react-containers/assets/143773/825cc6b7-681d-4ec9-96a5-6220da97dab8
https://github.com/downshift-js/downshift/issues/1108
=> fix(combobox): workaround Downshift cursor bug

package-lock.json, packages/combobox/demo/stories/ComboboxStory.tsx, packages/combobox/src/ComboboxContainer.spec.tsx, packages/combobox/src/ComboboxContainer.tsx, packages/combobox/src/types.ts, packages/combobox/src/useCombobox.ts, packages/combobox/src/utils.ts
`container-combobox` has allowed consumers to set `option.value` with an `object` for ergonomics. This has proven to create unintended mismatches to selected values, and so this PR removes that compatibility feature, instead preferring all `value`s to be strings for the best comparison.
- ~~:guardsman: includes new unit tests~~
- ~~:wheelchair: tested for [WCAG 2.1](https://www.w3.org/TR/WCAG21) AA compliance
=> feat(combobox)!: prefer strings as option values

.storybook/preview.js, packages/menu/README.md, packages/menu/demo/stories/MenuStory.tsx, packages/menu/demo/stories/data.ts, packages/menu/src/MenuContainer.spec.tsx, packages/menu/src/types.ts, packages/menu/src/useMenu.ts, packages/menu/src/utils.ts, packages/selection/src/types.ts, packages/selection/src/useSelection.ts
Allows a consumer of `useMenu` to set `href` and `isExternal` for automatic attribute handling. Based on the RFC published last year.
This will be followed up with a PR in `react-components` to consume an alternate `Item` DOM to use anchors in this use-case.
=> feat(menu): adds support for link items

packages/menu/src/MenuContainer.spec.tsx, packages/menu/src/useMenu.ts
Currently, setting a `defaultFocusedValue` causes unexpected focus into the menu when the trigger is clicked with a mouse.
The way `defaultFocusedValue` should operate today is to only focus an item when the menu opens with keyboard interaction (from the trigger).
Instead, because `useReducer` initializes with `defaultFocusedValue`, a menu first opens with that value selected, including mouse interaction.
This behavior is intended to match [APG examples](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-editor/) which prefer moving focus into menus only when an item is hovered. 
Note the below demonstration that showcases `Hydrangea` as the default focused value before and after the fix.
Before:
https://github.com/user-attachments/assets/ebcc853b-39a1-4c0d-af18-c2c8c6c3f6fa …
=> fix(menu): prevents `defaultFocusedValue` on trigger click

packages/menu/src/MenuContainer.spec.tsx, packages/menu/src/MenuContainer.tsx, packages/menu/src/types.ts, packages/menu/src/useMenu.ts
Improve the logic for returning focus to trigger. Adds optional `restoreFocus` prop to manager focus return to trigger. 
A new `restoreFocus` prop has been added. By default `restoreFocus` is `true` and will return the focus to the trigger on menu item selection, `ESC` / `TAB` key press, and clicking outside the menu dropdown. User who need to keep the dropdown open on selection must set `restoreFocus={false}` and manually handle the focus return.
- Returning focus to trigger is now executed synchronously before calling the `onChange` callback. Now, when a menu item triggers Garden's [Modal](https://garden.zendesk.com/components/modal) open, the focus will automatically be restored to the menu trigger after the modal has closed.
https://github.com/user-attachments/assets/ce921dbf-1c40-4d01 …
=> fix(container-menu)!: improves logic for returning focus to trigger

packages/menu/README.md, packages/menu/demo/menu.stories.tsx, packages/menu/demo/stories/MenuStory.tsx, packages/menu/demo/stories/data.ts, packages/menu/src/MenuContainer.spec.tsx, packages/menu/src/types.ts, packages/menu/src/useMenu.ts, packages/menu/src/utils.ts
This PR updates the `useMenu` API by decoupling anchor-related logic from `getItemProps`. It introduces a new `getAnchorProps` getter for handling anchor-specific attributes in navigational menus. This PR is to supersede #693.
- `getItemProps` no longer includes anchor-related props. Use `getAnchorProps` for `<a>` tags.
- Continue using `getItemProps` for `<li>`-level attributes around anchor items.
- `useMenu` no longer tracks selected link state internally. Consumers must now:
- Mark items as selected by default with `selected: true`, or
- Use `props.selectedItems` (overrides items selected by default)
`getAnchorProps` behavior:
- Returns anchor attributes (href, target, rel, etc.) for items with an `href`.
- Adds `target="_blank"` and `rel="noreferrer noopener"` when `external` is …
=> feat(container-menu)!: Add getAnchorProps for explicit anchor handling
