zendeskgarden/react-containers

.github/PULL_REQUEST_TEMPLATE.md
=> chore: add a11y item to PR Template checklist

packages/focusjail/src/FocusJailContainer.spec.js
When switching to react-testing-library #36 the code coverage for `useFocusJail` dropped.
Turns out I was triggering events on the wrong thing for most of the coverage drop. Added a missing branch to bring statement coverage up to 100%.
=> chore(testing): Increase coverage of useFocusJail

.storybook/config.js, package.json, yarn.lock
Pre-publish shows `zendesk.svg` rendering properly: https://garden.zendesk.com/react-containers/storybook/?path=/story/accordion-container--useaccordion
=> fix(demo): storybook brand image

package.json, yarn.lock
Duplicate keys in package.json when I did a merge conflict fix after a rebase.
=> fix: Duplicate dependencies listed in package.json

packages/selection/src/useSelection.js
While migrating `@zendeskgarden/react-pagination` to use the `PaginationContainer` I found some blocking issues when trying to control the focus/selected values of all the render-prop containers within `react-containers`.
This PR corrects the root problem found within `useSelection` allowing all hooks and containers to be controlled correctly.
For some use-cases controlling the `focusedItem` and `selectedItem` caused race-conditions, multiple renders, and infinite loops. An example is the current `PaginationContainer` example in the docs:
Here you can see some elements being skipped in the logic. Attempting to further control the input blows up the stack.
I was able to trace these issues to how we create our state reducer in `useSelection`. By creating out reducer function inline with the …
=> fix(selection): reducer number of renders when controlled

packages/focusvisible/README.md
=> fix(focusvisible): invalid import in README example code

README.md
Slipped through with #148.
Fixes broken build: https://travis-ci.com/zendeskgarden/react-containers/builds/144828743
=> fix: format README

.circleci/config.yml
- Reduce concurrency to prevent kill signal
- Restore coveralls reporting
=> chore: optimize CircleCI config

.circleci/config.yml
Remove unnecessary tag filters.
=> chore: clean up CircleCI config

.circleci/config.yml, utils/scripts/gh-pages.js
- Add commit user
- Skip CI on gh-pages branch
- Persist coverage for deploy
=> chore: update gh-pages deploy config

.circleci/config.yml, package.json
Following on zendeskgarden/react-components#683
=> fix: use default CircleCI node_modules cache

.circleci/config.yml, package.json, utils/scripts/deploy.js, yarn.lock
Use `writer` env variable context for deploy and exit with error if deployment fails.
=> chore: deploy context and error reporting

.circleci/config.yml, .gitignore, package.json, utils/test/jest.config.js
Restore the `/coverage/lcov-report` that was lost during the transition to storybook.
=> chore(demo): restore coverage report

package.json
Ensures that the tag stamped by `yarn run tag` is, indeed, the desired commit tag.
Parity with https://github.com/zendeskgarden/react-components/pull/753
=> chore(scripts): force version tag

package.json, utils/scripts/deploy.js, yarn.lock
Verify available Netlify bandwidth prior to staging deploy.
=> chore(scripts): enhance deploy with added bandwidth checking

.github/renovate.json, package.json, packages/accordion/yarn.lock, packages/buttongroup/yarn.lock, packages/focusjail/yarn.lock, packages/keyboardfocus/yarn.lock, packages/modal/yarn.lock, packages/pagination/yarn.lock, packages/selection/yarn.lock, packages/tabs/yarn.lock, packages/tooltip/yarn.lock
- update schedule to match internal documentation
- add yarn dedupe
- update `version` script to keep package lockfiles in sync
=> chore: update renovate configuration

packages/treeview/yarn.lock
Fix for CI failure.
https://app.circleci.com/pipelines/github/zendeskgarden/react-containers/1982/workflows/9a68d65e-f53e-455b-b5c5-7eaf0dd88704/jobs/3919/parallel-runs/0/steps/0-103
=> fix(treeview): update yarn.lock

.storybook/preview.js
Parity with https://github.com/zendeskgarden/react-components/pull/1459
=> chore(demo): prevent strict mode tool in production Storybook

packages/accordion/.size-snapshot.json, packages/buttongroup/.size-snapshot.json, packages/field/.size-snapshot.json, packages/focusjail/.size-snapshot.json, packages/focusvisible/.size-snapshot.json, packages/grid/.size-snapshot.json, packages/keyboardfocus/.size-snapshot.json, packages/modal/.size-snapshot.json, packages/pagination/.size-snapshot.json, packages/schedule/.size-snapshot.json, packages/scrollregion/.size-snapshot.json, packages/selection/.size-snapshot.json, packages/slider/.size-snapshot.json, packages/splitter/.size-snapshot.json, packages/tabs/.size-snapshot.json, packages/tooltip/.size-snapshot.json, packages/treeview/.size-snapshot.json, packages/utilities/.size-snapshot.json
Fix `.size-snapshot.json` files currently out-of-sync on `main`.
=> fix: update size snapshots

.circleci/config.yml
See:
- https://circleci.com/developer/orbs/orb/circleci/node#commands-install-packages
- https://support.circleci.com/hc/en-us/articles/115015426888-Clear-Project-Dependency-Cache
=> chore: add version for clearing corrupted CI cache

packages/accordion/yarn.lock, packages/buttongroup/yarn.lock, packages/combobox/yarn.lock, packages/field/yarn.lock, packages/focusjail/yarn.lock, packages/grid/yarn.lock, packages/keyboardfocus/yarn.lock, packages/modal/yarn.lock, packages/pagination/yarn.lock, packages/selection/yarn.lock, packages/splitter/yarn.lock, packages/tabs/yarn.lock, packages/tooltip/yarn.lock, packages/treeview/yarn.lock
Syncing the yarn lock files after latest dependency update to packages.
=> chore(deps): sync lock files for packages

packages/accordion/yarn.lock, packages/combobox/yarn.lock, packages/field/yarn.lock, packages/focusjail/yarn.lock, packages/grid/yarn.lock, packages/keyboardfocus/yarn.lock, packages/modal/yarn.lock, packages/selection/yarn.lock, packages/splitter/yarn.lock, packages/tabs/yarn.lock, packages/tooltip/yarn.lock
Syncing `yarn.lock` files for packages.
=> chore(deps): sync package lock files

package.json, yarn.lock
Removes unused and deprecated dependencies in the root of the project.
=> chore(deps): prune deprecated and unused dependencies

packages/accordion/yarn.lock
Sync lock file for `accordion` package.
=> chore(accordions): sync lock file

packages/accordion/CHANGELOG.md
Amending the `CHANGELOG` for `container-accordion` v3.
=> chore(accordion): amend changelog for v3

packages/menu/package.json
=> chore(deps): remove unneeded dev dependency in container-menu

packages/utilities/src/utils/DocumentPosition.ts, packages/utilities/src/utils/KeyboardEventValues.ts
...in prep for subsequent deletion. There will be a patch release after this PR, followed by a major release when these utilities have been deleted.
=> chore(utilities): deprecate `DocumentPosition` and `KEY_CODES`

package-lock.json, packages/.template/package.json, packages/accordion/package.json, packages/breadcrumb/package.json, packages/combobox/package.json, packages/field/package.json, packages/focusjail/package.json, packages/focusvisible/package.json, packages/grid/package.json, packages/menu/package.json, packages/modal/package.json, packages/schedule/package.json, packages/scrollregion/package.json, packages/selection/package.json, packages/slider/package.json, packages/splitter/package.json, packages/tabs/package.json, packages/tooltip/package.json, packages/utilities/package.json
Analog of https://github.com/zendeskgarden/react-components/pull/1893 for `react-containers`
=> fix: React peer dependency ranges

.github/renovate.json, README.md
Shift for `tailwindcss` dependency.
=> chore: update renovate schedule
